name: GitHub Server Speedtest

on:
  workflow_dispatch:

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python package
        run: |
          pip install speedtest-cli

      - name: Run Speedtest
        run: |
          speedtest-cli
